#!/usr/bin/env bash
export HTTP_PROXY=http://127.0.0.1:17997
export HTTPS_PROXY=http://127.0.0.1:17997
export http_proxy="$HTTP_PROXY"
export https_proxy="$HTTPS_PROXY"
export NO_PROXY=localhost,127.0.0.1,::1
export no_proxy="$NO_PROXY"
export CONDA_PKGS_DIRS=/mnt/wxh/go2_short_vln/caches/conda/pkgs
export PIP_CACHE_DIR=/mnt/wxh/go2_short_vln/caches/pip
export XDG_CACHE_HOME=/mnt/wxh/go2_short_vln/caches/xdg
export HF_HOME=/mnt/wxh/go2_short_vln/caches/huggingface
export TORCH_HOME=/mnt/wxh/go2_short_vln/caches/torch
export TMPDIR=/mnt/wxh/go2_short_vln/tmp
export PYTHONNOUSERSITE=1
