robot:
  name: unitree_go2
  motion_backend: root_kinematic
  asset_path: ""
  asset_cache_dir: ""
  base_height: 0.40
  init_pose_range:
    x: [-2.5, 2.5]
    y: [-2.5, 2.5]
    yaw_deg: [-180.0, 180.0]
  low_level_policy:
    enabled: false
    checkpoint: ""

camera:
  width: 640
  height: 480
  enable_depth: false
  depth_data_type: distance_to_image_plane
  depth_min: 0.20
  depth_max: 10.0
  depth_invalid_fill_value: 0.0
  focal_length: 24.0
  focus_distance: 400.0
  horizontal_aperture: 25.223161290244985
  clipping_range: [0.20, 10.0]
  mount_prim_path: "{ENV_REGEX_NS}/Robot/base/front_camera_sensor"
  offset:
    pos: [0.32715, -0.00003, 0.04297]
    rot: [0.5, -0.5, 0.5, -0.5]
    convention: ros
