targets:
  orin:
    jump_host: z786@172.22.25.155
    target_host: unitree@192.168.123.18
    remote_base: /home/unitree/unitree_go2
    remote_repo_dir: /home/unitree/unitree_go2/go2_vla_collector
    remote_sdk_dir: /home/unitree/unitree_go2/unitree_sdk2
  pd:
    jump_host: z786@172.22.25.155
    target_host: xiaohui@10.211.55.3
    remote_base: /home/xiaohui/unitree_go2
    remote_repo_dir: /home/xiaohui/unitree_go2/go2_real_collector
    remote_sdk_dir: /home/xiaohui/unitree_go2/unitree_sdk2
